# Generated by Django 4.2.5 on 2023-09-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_image_movie_mage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='mage',
            new_name='image',
        ),
    ]
